import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parse as parseYaml } from 'yaml';
import { runCodegen, type CliIo } from '../cli/src/index.js';

const REPO_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const EXAMPLES_DIR = path.join(REPO_ROOT, 'examples');

class CapturedIo implements CliIo {
  stdoutBuf = '';
  stderrBuf = '';

  constructor(public cwd: string) {}

  get stdout() {
    return {
      write: (s: string): boolean => {
        this.stdoutBuf += s;
        return true;
      },
    };
  }

  get stderr() {
    return {
      write: (s: string): boolean => {
        this.stderrBuf += s;
        return true;
      },
    };
  }
}

async function listExamples(): Promise<string[]> {
  const entries = await readdir(EXAMPLES_DIR, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => path.join(EXAMPLES_DIR, e.name))
    .sort();
}

describe('examples — registry shape', () => {
  it('every directory under examples/ ships subgraph.yaml + schema.graphql + src/mapping.ts + README.md', async () => {
    const dirs = await listExamples();
    expect(dirs.length).toBeGreaterThan(0);
    for (const dir of dirs) {
      for (const rel of [
        'subgraph.yaml',
        'schema.graphql',
        'src/mapping.ts',
        'README.md',
      ]) {
        const p = path.join(dir, rel);
        const s = await stat(p);
        expect(s.isFile(), `${rel} missing in ${path.basename(dir)}`).toBe(true);
      }
    }
  });

  it('every subgraph.yaml parses + carries the expected top-level shape', async () => {
    const dirs = await listExamples();
    for (const dir of dirs) {
      const raw = await readFile(path.join(dir, 'subgraph.yaml'), 'utf8');
      const manifest = parseYaml(raw) as Record<string, unknown>;
      expect(typeof manifest.name).toBe('string');
      expect(typeof manifest.specVersion).toBe('string');
      expect(manifest.schema).toMatchObject({ file: './schema.graphql' });
      expect(Array.isArray(manifest.dataSources)).toBe(true);
      for (const ds of manifest.dataSources as Array<Record<string, unknown>>) {
        expect(typeof ds.name).toBe('string');
        expect(typeof ds.network).toBe('string');
        expect(typeof ds.kind).toBe('string');
        const mapping = ds.mapping as { file: string; handlers: unknown[] };
        expect(typeof mapping.file).toBe('string');
        expect(Array.isArray(mapping.handlers)).toBe(true);
      }
    }
  });

  it('every dataSources[].source uses only the documented data-source kinds', async () => {
    const dirs = await listExamples();
    const allowed = new Set(['covenant_id', 'krc20', 'krc721', 'address', 'utxo']);
    for (const dir of dirs) {
      const manifest = parseYaml(
        await readFile(path.join(dir, 'subgraph.yaml'), 'utf8'),
      ) as { dataSources: Array<{ kind: string }> };
      for (const ds of manifest.dataSources) {
        expect(
          allowed.has(ds.kind),
          `${path.basename(dir)} uses unknown kind \`${ds.kind}\``,
        ).toBe(true);
      }
    }
  });
});

describe('examples — kasgraph codegen', () => {
  it.each(['kasbonds', 'opensilver-patterns', 'krc20', 'krc721', 'network-stats', 'zk-proofs'])(
    'codegen against examples/%s produces generated entities + events',
    async (name) => {
      const dir = path.join(EXAMPLES_DIR, name);
      const io = new CapturedIo(dir);
      const code = await runCodegen([], io);
      expect(code, io.stderrBuf || io.stdoutBuf).toBe(0);

      const entities = await readFile(
        path.join(dir, 'src/generated/entities.ts'),
        'utf8',
      );
      const events = await readFile(
        path.join(dir, 'src/generated/events.ts'),
        'utf8',
      );

      // Both files exist and carry the generated banner.
      expect(entities).toContain('Generated by `kasgraph codegen`');
      expect(events).toContain('Generated by `kasgraph codegen`');

      // Per-example assertions on what should land.
      if (name === 'kasbonds') {
        expect(entities).toContain('export interface Bond');
        expect(entities).toContain('export interface Holding');
        expect(entities).toContain('export interface Coupon');
        // Handlers in the manifest → event interfaces in generated/events.ts.
        expect(events).toContain('export interface CovenantLockedEvent');
        expect(events).toContain('export interface CovenantSpentEvent');
      }
      if (name === 'opensilver-patterns') {
        expect(entities).toContain('export interface PatternInstance');
        expect(entities).toContain('export interface VaultInstance');
        expect(entities).toContain('export interface MultisigInstance');
        expect(entities).toContain('export interface EscrowInstance');
      }
      if (name === 'krc20') {
        expect(entities).toContain('export interface KCC20Asset');
        expect(entities).toContain('export interface KCC20Controller');
        expect(entities).toContain('export interface KCC20Holder');
        expect(entities).toContain('export interface KCC20Transfer');
        expect(entities).toContain('export interface KCC20Mint');
        // All five KCC20 patterns are registered → typed payload union.
        expect(events).toContain('export interface KCC20AssetState');
        expect(events).toContain('detectorKind: "KCC20Asset";');
        expect(events).toContain('| KCC20VestingControllerState;');
        expect(events).not.toContain('payload: unknown;');
        // CovenantSpent carries the protocol-level spend envelope.
        expect(events).toContain('export interface CovenantSpend');
        expect(events).toContain('payload: { spend: CovenantSpend; state:');
      }
      if (name === 'krc721') {
        expect(entities).toContain('export interface KRC721Collection');
        expect(entities).toContain('export interface KRC721Token');
        expect(entities).toContain('export interface KRC721Holder');
        expect(entities).toContain('export interface KRC721Mint');
        expect(entities).toContain('export interface KRC721Transfer');
        // NFT-semantic handlers → event interfaces.
        expect(events).toContain('export interface CollectionDeployedEvent');
        expect(events).toContain('export interface NftMintedEvent');
        expect(events).toContain('export interface NftTransferredEvent');
        expect(events).toContain('export interface NftBurnedEvent');
        // `krc721` collection source carries no detector patterns.
        expect(events).toContain('payload: unknown;');
      }
      if (name === 'network-stats') {
        expect(entities).toContain('export interface BlockStat');
        expect(entities).toContain('export interface DailyStat');
        expect(entities).toContain('export interface AddressActivity');
        expect(events).toContain('export interface BlockAddedEvent');
        expect(events).toContain('export interface UtxoChangedEvent');
        // `utxo` firehose carries no detector patterns.
        expect(events).toContain('payload: unknown;');
      }
      if (name === 'zk-proofs') {
        expect(entities).toContain('export interface ZkVerifyingKey');
        expect(entities).toContain('export interface ZkProof');
        expect(entities).toContain('export interface ZkWitness');
        expect(entities).toContain('export interface ZkVerification');
        expect(events).toContain('export interface CovenantLockedEvent');
        expect(events).toContain('export interface CovenantSpentEvent');
        // ZK-aware detector patterns aren't registered yet, so the
        // CovenantLocked state stays `unknown`...
        expect(events).toContain('payload: unknown;');
        // ...but the CovenantSpent event still gets the spend envelope
        // (protocol-level, registry-independent) with `state: unknown`.
        expect(events).toContain('export interface CovenantSpend');
        expect(events).toContain('payload: { spend: CovenantSpend; state: unknown };');
      }
    },
  );

  it('generated event interfaces match every handler.event name in the manifest', async () => {
    const dirs = await listExamples();
    for (const dir of dirs) {
      const manifest = parseYaml(
        await readFile(path.join(dir, 'subgraph.yaml'), 'utf8'),
      ) as { dataSources: Array<{ mapping: { handlers: Array<{ event: string }> } }> };
      const eventsBody = await readFile(
        path.join(dir, 'src/generated/events.ts'),
        'utf8',
      );
      for (const ds of manifest.dataSources) {
        for (const handler of ds.mapping.handlers) {
          expect(
            eventsBody,
            `${path.basename(dir)} events.ts missing ${handler.event}Event`,
          ).toContain(`export interface ${handler.event}Event`);
        }
      }
    }
  });
});
